# Generated by Django 2.1.1 on 2018-09-15 06:47

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='link',
            managers=[
                ('with_votes', django.db.models.manager.Manager()),
            ],
        ),
    ]
